import { randomUUID } from "crypto";
import { existsSync, readFileSync, writeFileSync, chmodSync, renameSync } from "fs";
import { join } from "path";
import type { EnsureStepResult, GitOps } from "./types";
import { getInstanceConfig, setInstanceConfig } from "./settings";
import { isPrivateInstance } from "./detect";

const DEFAULT_BRANCH_NAME = "local";

/**
 * Phase A step 1: ensure the instance config row exists with a stable instanceId.
 * Idempotent — returns early if config already exists.
 */
export async function ensureInstanceConfig(): Promise<EnsureStepResult> {
  const existing = getInstanceConfig();
  if (existing) {
    return { step: "instance-config", status: "skipped", reason: "already_exists" };
  }
  await setInstanceConfig({
    instanceId: randomUUID(),
    branchName: DEFAULT_BRANCH_NAME,
    isPrivateInstance: isPrivateInstance(),
    createdAt: Math.floor(Date.now() / 1000),
  });
  return { step: "instance-config", status: "ok" };
}

/**
 * Phase A step 2: create the `local` branch at current HEAD if it doesn't exist.
 * Non-destructive: `git checkout -b local` preserves whatever branch the user
 * was on, including any local commits. Safe on drifted-main scenarios.
 */
export function ensureLocalBranch(git: GitOps): EnsureStepResult {
  if (git.branchExists(DEFAULT_BRANCH_NAME)) {
    return { step: "local-branch", status: "skipped", reason: "branch_exists" };
  }
  try {
    git.createAndCheckoutBranch(DEFAULT_BRANCH_NAME);
    return { step: "local-branch", status: "ok" };
  } catch (err) {
    return {
      step: "local-branch",
      status: "failed",
      reason: err instanceof Error ? err.message : String(err),
    };
  }
}

export const STAGENT_HOOK_VERSION = "1.0.0";

/**
 * Pre-push hook template. Installed verbatim at .git/hooks/pre-push.
 *
 * Reads the blocked branch list from the stagent SQLite settings table
 * via a bounded sqlite3 invocation. The query is hardcoded — no user
 * input reaches the shell.
 *
 * Escape hatch: set ALLOW_PRIVATE_PUSH=1 in env to bypass the guardrail
 * for legitimate cherry-pick pushes.
 */
const PRE_PUSH_HOOK_TEMPLATE = `#!/bin/sh
# STAGENT_HOOK_VERSION=${STAGENT_HOOK_VERSION}
# Blocks pushes of private instance branches to origin.
# Escape hatch: ALLOW_PRIVATE_PUSH=1 git push ...
#
# Generated by src/lib/instance/bootstrap.ts — do not edit manually.

if [ "$ALLOW_PRIVATE_PUSH" = "1" ]; then
  exit 0
fi

current_branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
if [ -z "$current_branch" ]; then
  exit 0
fi

data_dir="\${STAGENT_DATA_DIR:-$HOME/.stagent}"
db_path="$data_dir/stagent.db"
if [ ! -f "$db_path" ] || ! command -v sqlite3 >/dev/null 2>&1; then
  exit 0
fi

blocked_json=$(sqlite3 "$db_path" "SELECT value FROM settings WHERE key='instance.guardrails';" 2>/dev/null)
if [ -z "$blocked_json" ]; then
  exit 0
fi

if echo "$blocked_json" | grep -q "\\"$current_branch\\""; then
  echo "stagent: refusing to push private instance branch '$current_branch' to origin." >&2
  echo "stagent: set ALLOW_PRIVATE_PUSH=1 to override (not recommended)." >&2
  exit 1
fi

exit 0
`;

/**
 * Phase B step 1: install the pre-push hook at .git/hooks/pre-push.
 * Idempotent: checks version marker in existing file; backs up foreign hooks.
 */
export function ensurePrePushHook(git: GitOps): EnsureStepResult {
  const hookPath = join(git.getGitDir(), "hooks", "pre-push");
  const markerLine = `STAGENT_HOOK_VERSION=${STAGENT_HOOK_VERSION}`;

  if (existsSync(hookPath)) {
    const existing = readFileSync(hookPath, "utf-8");
    if (existing.includes(markerLine)) {
      return { step: "pre-push-hook", status: "skipped", reason: "already_installed" };
    }
    if (existing.includes("STAGENT_HOOK_VERSION=")) {
      try {
        writeFileSync(hookPath, PRE_PUSH_HOOK_TEMPLATE, { mode: 0o755 });
        return { step: "pre-push-hook", status: "ok", reason: "upgraded" };
      } catch (err) {
        return {
          step: "pre-push-hook",
          status: "failed",
          reason: err instanceof Error ? err.message : String(err),
        };
      }
    }
    try {
      renameSync(hookPath, `${hookPath}.stagent-backup`);
    } catch (err) {
      return {
        step: "pre-push-hook",
        status: "failed",
        reason: `backup_failed: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }

  try {
    writeFileSync(hookPath, PRE_PUSH_HOOK_TEMPLATE, { mode: 0o755 });
    chmodSync(hookPath, 0o755);
    return { step: "pre-push-hook", status: "ok" };
  } catch (err) {
    return {
      step: "pre-push-hook",
      status: "failed",
      reason: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Phase B step 2: set branch.<name>.pushRemote=no_push for each blocked branch.
 * Idempotent via git config semantics (setting the same value is a no-op).
 */
export function ensureBranchPushConfig(git: GitOps, branches: string[]): EnsureStepResult {
  const failures: string[] = [];
  for (const branch of branches) {
    try {
      git.setConfig(`branch.${branch}.pushRemote`, "no_push");
    } catch (err) {
      failures.push(`${branch}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  if (failures.length > 0) {
    return {
      step: "branch-push-config",
      status: "failed",
      reason: failures.join("; "),
    };
  }
  return { step: "branch-push-config", status: "ok" };
}
