/**
 * Cloud license validation via Supabase Edge Function.
 *
 * Calls the validate-license Edge Function to check if the user's
 * email has an active subscription. Uses the same Supabase client
 * defaults as supabase-client.ts (production backend by default).
 */

import { isCloudConfigured, getSupabaseUrl, getSupabaseAnonKey } from "@/lib/cloud/supabase-client";
import type { LicenseTier } from "./tier-limits";

export type SeatStatus = "ok" | "over_limit" | "grace";

export interface CloudValidationResult {
  valid: boolean;
  tier: LicenseTier;
  expiresAt?: Date;
  error?: string;
  /** Optional seat status from the server. Missing = "ok" (backward-compatible). */
  seatStatus?: SeatStatus;
}

export interface CloudValidationInput {
  email: string;
  /** Stable per-machine fingerprint. Non-identifying hash. See TDR-030. */
  machineFingerprint?: string;
  /** Per-clone UUID generated by instance-bootstrap. Survives `Clear All Data`. */
  instanceId?: string;
}

/**
 * Validate a license against the cloud backend.
 * Returns { valid: false } if cloud is disabled or email is empty.
 *
 * The machineFingerprint + instanceId tuple lets the edge function meter
 * seats per (email, machine, clone) — see TDR-030 hybrid instance licensing.
 * Both are optional for backward compatibility with callers that don't yet
 * pass them; the server accepts missing fields as if the client were on
 * an older build.
 */
export async function validateLicenseWithCloud(
  input: string | CloudValidationInput
): Promise<CloudValidationResult> {
  // Accept the legacy string-email signature for backward compatibility.
  const payload: CloudValidationInput =
    typeof input === "string" ? { email: input } : input;

  if (!isCloudConfigured() || !payload.email) {
    return { valid: false, tier: "community", error: "Cloud disabled or no email" };
  }

  const supabaseUrl = getSupabaseUrl();
  const anonKey = getSupabaseAnonKey();

  try {
    const response = await fetch(`${supabaseUrl}/functions/v1/validate-license`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anonKey}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      return { valid: false, tier: "community", error: `HTTP ${response.status}` };
    }

    const data = await response.json();
    return {
      valid: data.valid === true,
      tier: data.tier ?? "community",
      expiresAt: data.expiresAt ? new Date(data.expiresAt) : undefined,
      seatStatus: isSeatStatus(data.seatStatus) ? data.seatStatus : undefined,
    };
  } catch (err) {
    return {
      valid: false,
      tier: "community",
      error: err instanceof Error ? err.message : "Unknown error",
    };
  }
}

function isSeatStatus(value: unknown): value is SeatStatus {
  return value === "ok" || value === "over_limit" || value === "grace";
}
