/**
 * Profile generator: turns rule-based suggestions into actual agent profiles.
 */

import { getArtifacts } from "./data";
import { evaluateRules, generateTier2Suggestions, type ProfileSuggestion } from "./profile-rules";
import { listProfiles, createProfile } from "@/lib/agents/profiles/registry";
import type { ProfileConfig } from "@/lib/validators/profile";

const MIN_CURATED_CONFIDENCE = 0.6;

export interface TieredSuggestions {
  curated: ProfileSuggestion[];
  discovered: ProfileSuggestion[];
}

/**
 * Suggest profiles based on artifacts from a scan.
 * Returns both curated (Tier 1) and discovered (Tier 2) suggestions.
 * Filters out suggestions that match existing profiles.
 */
export function suggestProfilesTiered(scanId: string): TieredSuggestions {
  const artifacts = getArtifacts({ scanId });

  // Tier 1: Curated rules
  const curatedRaw = evaluateRules(artifacts);
  const existing = listProfiles();
  const existingIds = new Set(existing.map((p) => p.id));
  const existingNames = new Set(existing.map((p) => p.name.toLowerCase()));

  const curated = curatedRaw
    .filter((s) => s.confidence >= MIN_CURATED_CONFIDENCE)
    .filter(
      (s) => !existingIds.has(s.ruleId) && !existingNames.has(s.name.toLowerCase())
    );

  // Tier 2: Unlinked skill artifacts (those without linkedProfileId)
  const unlinkedSkills = artifacts.filter(
    (a) => a.category === "skill" && !a.linkedProfileId
  );
  const discovered = generateTier2Suggestions(unlinkedSkills).filter(
    (s) =>
      !existingIds.has(s.ruleId) &&
      !existingIds.has(`env-${s.ruleId}`) &&
      !existingNames.has(s.name.toLowerCase())
  );

  return { curated, discovered };
}

/**
 * Suggest profiles based on artifacts from a scan (legacy flat API).
 * Returns only curated (Tier 1) suggestions for backward compatibility.
 */
export function suggestProfiles(scanId: string): ProfileSuggestion[] {
  return suggestProfilesTiered(scanId).curated;
}

/**
 * Generate a ProfileConfig from a suggestion.
 */
export function generateProfileConfig(suggestion: ProfileSuggestion): ProfileConfig {
  return {
    id: `env-${suggestion.ruleId}`,
    name: suggestion.name,
    version: "1.0.0",
    domain: "work",
    tags: suggestion.tags,
    supportedRuntimes: ["claude-code"],
    allowedTools: suggestion.suggestedTools,
    canUseToolPolicy: {
      autoApprove: ["Read", "Grep", "Glob"],
      autoDeny: [],
    },
    maxTurns: 30,
    author: "stagent-env",
    tests: [
      {
        task: `Perform a ${suggestion.name.toLowerCase()} task`,
        expectedKeywords: suggestion.tags.slice(0, 3),
      },
    ],
  };
}

/**
 * Generate a SKILL.md from a suggestion.
 */
export function generateSkillMd(suggestion: ProfileSuggestion): string {
  const lines = [
    "---",
    `name: ${suggestion.name}`,
    `description: ${suggestion.description}`,
    "---",
    "",
    suggestion.systemPrompt,
    "",
    "## Matched Artifacts",
    "",
    ...suggestion.matchedArtifacts.map(
      (a) => `- **${a.name}** (${a.category})`
    ),
    "",
    `> Auto-generated by Stagent environment scanner with ${Math.round(suggestion.confidence * 100)}% confidence.`,
  ];

  return lines.join("\n");
}

/**
 * Create a profile from a suggestion — writes to ~/.claude/skills/ and registers.
 */
export function createProfileFromSuggestion(
  suggestion: ProfileSuggestion,
  overrides?: { name?: string; description?: string; systemPrompt?: string }
): void {
  const config = generateProfileConfig(suggestion);
  let skillMd = generateSkillMd(suggestion);

  // Apply overrides
  if (overrides?.name) config.name = overrides.name;
  if (overrides?.systemPrompt) {
    skillMd = skillMd.replace(suggestion.systemPrompt, overrides.systemPrompt);
  }

  createProfile(config, skillMd);

  // Note: the created profile will have author "stagent-env" which,
  // combined with the env- prefix on the ID, identifies it as environment-originated.
  // The profile registry can infer origin from the author field.
}
